[phases.setup]
nixPkgs = ["...", "zlib", "libjpeg", "libpng", "freetype"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn superrecord.wsgi --bind 0.0.0.0:$PORT"
