# Generated by Django 4.2.30 on 2026-08-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0023_stockbatch_expiration_date_and_more'),
        ('granel', '0017_convert_precio_cuarto_to_kilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caramelera',
            name='productos_autorizados',
            field=models.ManyToManyField(blank=True, help_text='Productos del inventario marcados como "para venta por peso" que pueden entrar en este mix', limit_choices_to={'es_deposito_caramelera': True}, to='stocks.product', verbose_name='Productos Autorizados'),
        ),
    ]
