# Generated by Django 4.2.30 on 2026-09-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0027_alter_venta_por_peso_metadata'),
        ('granel', '0019_resync_granel_pos_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caramelera',
            name='productos_autorizados',
            field=models.ManyToManyField(blank=True, help_text='Productos del inventario que pueden entrar en este mix (sistema viejo, histórico)', to='stocks.product', verbose_name='Productos Autorizados'),
        ),
    ]
