# Generated by Django 4.2.30 on 2026-09-15 09:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0023_stockbatch_expiration_date_and_more'),
        ('purchase', '0005_purchaseitem_packaging_alter_purchaseitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='order_day',
            field=models.CharField(blank=True, choices=[('mon', 'Lunes'), ('tue', 'Martes'), ('wed', 'Miércoles'), ('thu', 'Jueves'), ('fri', 'Viernes'), ('sat', 'Sábado'), ('sun', 'Domingo')], help_text='Día habitual en que se le hacen pedidos a este proveedor (para el aviso de pedido sugerido).', max_length=3, verbose_name='Día de Pedido'),
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio al que este proveedor vende el producto.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Precio de Compra')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_links', to='stocks.product', verbose_name='Producto')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='purchase.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Producto de Proveedor',
                'verbose_name_plural': 'Productos de Proveedor',
                'ordering': ['supplier__name', 'product__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='supplierproduct',
            constraint=models.UniqueConstraint(fields=('supplier', 'product'), name='unique_supplier_product'),
        ),
    ]
