# Generated by Django 4.2.27 on 2026-04-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadopago', '0002_alter_mpcredentials_id_alter_pointdevice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointdevice',
            name='external_pos_id',
            field=models.CharField(blank=True, help_text='ID externo para QR dinámico (se genera automáticamente)', max_length=100, verbose_name='External POS ID'),
        ),
    ]
