# Generated by Django 3.0.5 on 2026-02-03 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('template_type', models.CharField(choices=[('price', 'Precio Simple'), ('offer', 'Oferta'), ('promotion', 'Promoción'), ('combo', 'Combo'), ('custom', 'Personalizado')], max_length=20, verbose_name='Tipo')),
                ('size', models.CharField(choices=[('A4', 'A4 (210x297mm)'), ('A5', 'A5 (148x210mm)'), ('10x15', '10x15 cm'), ('custom', 'Personalizado')], default='A4', max_length=20, verbose_name='Tamaño')),
                ('orientation', models.CharField(choices=[('portrait', 'Vertical'), ('landscape', 'Horizontal')], default='portrait', max_length=20, verbose_name='Orientación')),
                ('layout_json', models.TextField(blank=True, default='{}', help_text='JSON con la configuración del diseño', verbose_name='Configuración de Diseño')),
                ('is_default', models.BooleanField(default=False, verbose_name='Por Defecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Plantilla de Cartel',
                'verbose_name_plural': 'Plantillas de Carteles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SignGeneration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='signs/', verbose_name='Archivo PDF')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='signs/previews/', verbose_name='Vista Previa')),
                ('config_json', models.TextField(blank=True, default='{}', help_text='JSON con la configuración del cartel', verbose_name='Configuración')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sign_generations', to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
                ('products', models.ManyToManyField(related_name='sign_generations', to='stocks.Product', verbose_name='Productos')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='signage.SignTemplate', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Cartel Generado',
                'verbose_name_plural': 'Carteles Generados',
                'ordering': ['-generated_at'],
            },
        ),
    ]
