# Generated by Django 3.0.5 on 2026-02-03 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
        ('stocks', '0002_add_bulk_and_parent_fields'),
        ('signage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signgeneration',
            name='custom_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Texto Personalizado'),
        ),
        migrations.AddField(
            model_name='signgeneration',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sign_generations', to='promotions.Promotion', verbose_name='Promoción'),
        ),
        migrations.AddField(
            model_name='signgeneration',
            name='sign_size',
            field=models.CharField(choices=[('A4', 'A4 - Grande'), ('A5', 'A5 - Mediano'), ('10x15', '10x15 - Pequeño')], default='A4', max_length=20, verbose_name='Tamaño'),
        ),
        migrations.AddField(
            model_name='signgeneration',
            name='sign_type',
            field=models.CharField(choices=[('price', 'Precio Simple'), ('promotion', 'Promoción'), ('offer', 'Oferta'), ('custom', 'Personalizado')], default='price', max_length=20, verbose_name='Tipo de Cartel'),
        ),
        migrations.AlterField(
            model_name='signgeneration',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='sign_generations', to='stocks.Product', verbose_name='Productos'),
        ),
        migrations.AlterField(
            model_name='signgeneration',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='signage.SignTemplate', verbose_name='Plantilla'),
        ),
    ]
