# Generated by Django 4.2.27 on 2026-03-19 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0007_alter_stockmovement_quantity'),
        ('signage', '0002_auto_20260203_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_size', models.CharField(choices=[('A4', 'A4 (210×297mm)'), ('letter', 'Carta (216×279mm)'), ('legal', 'Oficio (216×356mm)')], default='A4', max_length=10, verbose_name='Tamaño de Papel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sign_batches', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Lote de Carteles',
                'verbose_name_plural': 'Lotes de Carteles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre Custom')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Custom')),
                ('gramaje', models.CharField(blank=True, max_length=50, verbose_name='Gramaje')),
                ('promo_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad Promo')),
                ('promo_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Promo')),
                ('package_type', models.CharField(blank=True, choices=[('caja', 'Caja'), ('bolsa', 'Bolsa'), ('pack', 'Pack'), ('display', 'Display')], max_length=20, verbose_name='Tipo Empaque')),
                ('quantity_per_package', models.CharField(blank=True, help_text='Ej: 30U, 1kg, 500g', max_length=50, verbose_name='Contenido Empaque')),
                ('price_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio 100g')),
                ('price_250g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio ¼kg')),
                ('price_1kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio 1kg')),
                ('copies', models.PositiveIntegerField(default=1, verbose_name='Copias')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='signage.signbatch', verbose_name='Lote')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sign_items', to='stocks.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Cartel Individual',
                'verbose_name_plural': 'Carteles Individuales',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='signtemplate',
            options={'ordering': ['template_type', 'name'], 'verbose_name': 'Plantilla de Cartel', 'verbose_name_plural': 'Plantillas de Carteles'},
        ),
        migrations.RemoveField(
            model_name='signtemplate',
            name='orientation',
        ),
        migrations.RemoveField(
            model_name='signtemplate',
            name='size',
        ),
        migrations.AddField(
            model_name='signtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sign_templates', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='signtemplate',
            name='height_mm',
            field=models.PositiveIntegerField(default=40, verbose_name='Alto (mm)'),
        ),
        migrations.AddField(
            model_name='signtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AddField(
            model_name='signtemplate',
            name='width_mm',
            field=models.PositiveIntegerField(default=50, verbose_name='Ancho (mm)'),
        ),
        migrations.AlterField(
            model_name='signtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='signtemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='signtemplate',
            name='layout_json',
            field=models.TextField(blank=True, default='{}', help_text='JSON con toda la configuración visual del cartel', verbose_name='Configuración Visual'),
        ),
        migrations.AlterField(
            model_name='signtemplate',
            name='template_type',
            field=models.CharField(choices=[('simple', 'Precio Unitario'), ('promotional', 'Promocional (Llevá X por Y)'), ('bulk', 'Bulto Cerrado (Caja/Bolsa)'), ('weight', 'Venta al Peso (Dietética)')], max_length=20, verbose_name='Tipo de Cartel'),
        ),
        migrations.DeleteModel(
            name='SignGeneration',
        ),
        migrations.AddField(
            model_name='signbatch',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='signage.signtemplate', verbose_name='Plantilla'),
        ),
    ]
