# Generated by Django 4.2.30 on 2026-10-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_alter_assistantsettings_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantsettings',
            name='anthropic_api_key',
            field=models.CharField(blank=True, help_text='Clave de console.anthropic.com (sk-ant-...) — NO es la suscripción de Claude.ai, es una cuenta de API aparte, con su propia facturación. Usada solo por "Escanear Remito".', max_length=200, verbose_name='API Key de Claude (Anthropic)'),
        ),
        migrations.AddField(
            model_name='assistantsettings',
            name='anthropic_model',
            field=models.CharField(default='claude-sonnet-5', help_text='Modelo de Claude a usar para leer remitos', max_length=50, verbose_name='Modelo de Claude'),
        ),
        migrations.AlterField(
            model_name='assistantsettings',
            name='model',
            field=models.CharField(default='gemini-2.5-flash', help_text='Modelo de Gemini a usar (chat del asistente)', max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='assistantsettings',
            name='openai_api_key',
            field=models.CharField(blank=True, help_text='Clave API de Google Gemini (AIza...) — usada por el chat del asistente', max_length=200, verbose_name='API Key de Gemini'),
        ),
    ]
