# Generated by Django 4.2.30 on 2026-08-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0022_release_orphaned_packaging_barcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbatch',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='Opcional. Si el producto no vence, dejar en blanco.', null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='product',
            name='allow_sell_by_amount',
            field=models.BooleanField(default=False, help_text='Permite ingresar "$500 de producto" y calcular la cantidad', verbose_name='Permite Venta por Monto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='es_deposito_caramelera',
            field=models.BooleanField(default=False, help_text='Marca este producto como un bulto que puede abrirse hacia un producto fraccionado a granel', verbose_name='Es producto para venta por peso'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_granel',
            field=models.BooleanField(default=False, help_text='Producto comodín que recibe stock de bultos abiertos (ej: Jamón Cocido Fraccionado)', verbose_name='Producto Comodín Granel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='marca',
            field=models.CharField(blank=True, help_text='Marca del producto (útil para diferenciar bultos en la venta por peso)', max_length=200, verbose_name='Marca'),
        ),
    ]
