# Generated by Django 4.2.30 on 2026-09-25 12:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0023_stockbatch_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='oferta_price_250g',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Precio de oferta por 250g, en pesos. 0 = sin oferta (se cobra el precio normal).', max_digits=10, verbose_name='Precio de Oferta por 250g'),
        ),
        migrations.AddField(
            model_name='product',
            name='oferta_price_500g',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Precio de oferta por 500g, en pesos. 0 = sin oferta (se cobra el precio normal).', max_digits=10, verbose_name='Precio de Oferta por 500g'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price_500g',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Precio de venta por 500g (1/2 kg). 0 = calcularlo proporcional al precio por kilo.', max_digits=10, verbose_name='Precio por 500g'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price_250g',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Precio de venta por 250g (1/4 kg). 0 = calcularlo proporcional al precio por kilo.', max_digits=10, verbose_name='Precio por 250g'),
        ),
    ]
