# Generated by Django 4.2.30 on 2026-09-26 18:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0026_borrar_campos_viejos_venta_por_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_granel',
            field=models.BooleanField(default=False, help_text='Producto que se vende fraccionado por peso (fiambre, dietética, etc.)', verbose_name='Se vende por peso'),
        ),
        migrations.AlterField(
            model_name='product',
            name='marca',
            field=models.CharField(blank=True, help_text='Marca del producto (útil para diferenciar productos por peso del mismo tipo)', max_length=200, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_per_unit_grams',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Solo informativo: cuántos gramos pesa cada pieza al recibir mercadería', max_digits=10, verbose_name='Gramos por Pieza'),
        ),
    ]
