# Generated by Django 4.2.30 on 2026-09-26 19:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0027_alter_venta_por_peso_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price_100g',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Precio de venta por 100g para compras chicas (menos de 1/4 kilo) — normalmente más caro que el proporcional al precio por kilo, para compensar el trabajo extra de vender de a poco. 0 = calcularlo proporcional al precio por kilo (por defecto).', max_digits=10, verbose_name='Precio por 100g (menos de 1/4 kilo)'),
        ),
    ]
