# Generated by Django 4.2.30 on 2026-09-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0028_add_sale_price_100g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Alerta cuando el stock llegue a este nivel', max_digits=12, verbose_name='Stock Mínimo'),
        ),
    ]
